# Generated by Django 5.0.2 on 2024-03-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_jam_app", "0003_auto_20240301_0919"),
    ]

    operations = [
        migrations.AddField(
            model_name="tune",
            name="beats_per_minute",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tune",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="tune",
            name="notes",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
